[versions]

kotlin = "1.9.0"
kotlinx-coroutines = "1.7.2"
androidx-core = "1.12.0"
androidx-appcompat = "1.6.1"
androidx-activity = "1.7.2"
androidx-lifecycle = "2.6.2"
material = "1.9.0"
vico = "1.11.1"
meetacyDI = "0.0.25"

# compose
composeRuntime = "1.5.1"
composeUi = "1.5.1"
composeCompiler = "1.5.2"
composeNavigation = "2.7.2"
composeMaterial = "1.5.1"
composeActivity = "1.7.2"

[libraries]

material = { module = "com.google.android.material:material", version.ref = "material" }

# compose libs

compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "composeRuntime" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
compose-material = { module = "androidx.compose.material:material", version.ref = "composeMaterial" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }

# androidx libs

androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }


# vico charts

vico-core = { group = "com.patrykandpatrick.vico", name = "core", version.ref = "vico" }
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
vico-compose-m2 = { group = "com.patrykandpatrick.vico", name = "compose-m2", version.ref = "vico" }

# kotlinx libs

## coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

# other

mdi-compose = { module = "app.meetacy.di:compose", version.ref = "meetacyDI" }
mdi-android = { module = "app.meetacy.di:android", version.ref = "meetacyDI" }

# gradle

gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
